### ISSUE TITLE
Is your code based on DCGAN?

### ISSUE THREAD

**Issue by zhangrong1722** [TengdaHan/Image-Colorization#1]
Recently,I want to use discrimintor(one part of DCGAN) in my project.The size of images is 224x224.Fortunately,I found your code can be applied on such size.Could we have a further discussion  for details?
My QQ number is 1922525328.

thanks.

**Comment by TengdaHan** [comment]
Happy to discuss. What about wechat?

**Comment by zhangrong1722** [comment]
that's great.My wechat is zhangrong1728.What about you?Or could you add me directly?
Thanks.
